import type { Metadata } from "next";
import "./globals.scss";
import Navbar from "../components/Layout/Navbar";
import Footer from "../components/Layout/Footer";
import Header from "../components/Layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
